### PR TITLE
Feature prep v1.2.0 release

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This bumps the version number to 1.2.0 for the release.

### CODE REVIEW

**Comment by dgreene-r7** [comment]
:shipit:

But can we start including a `CHANGELOG.md` file? It'd be nice to maintain that and just c/p from it for the release notes.

**Comment by jmanero-r7** [comment]
Looks like this is several commits behind master. Rebase?

**Comment by fmitchell-r7** [comment]
@jmanero-r7 Thanks for catching that! I pulled in the latest changes from origin/master in https://github.com/rapid7/awsaml/pull/57/commits/5028c73f9d4ad1d954cd29be1e475b628f4b5437.

@dgreene-r7 Good idea! I added a CHANGELOG.md file in https://github.com/rapid7/awsaml/pull/57/commits/d3da52e3f1a423ef017663794e7834adff8e6ed4.

**Comment by jmanero-r7** [comment]
👍

**Comment by eciramella-r7** [comment]
Nice work!  Like having that Changelog!

**Pull request merged**
