### PR TITLE
Add Universal Binary support for Apple Silicon

### PR DESCRIPTION
**Pull request by ddavies-r7**
# What?
- Electron version update to 19.0.0
- Electron packager version update to 15.5.0
- Simplify post-build zip logic.
- Add Native Apple Silicon Support by way of a universal binary
- Modify build code to only impact darwin builds. Others are unaffected.

# Why?
This change allows for native execution of awsaml on ARM macs and addressed issue: https://github.com/rapid7/awsaml/issues/202
Native support removes translation of x64 code potentially increasing performance and battery life for the end user.
_NIT_ - Post build logic is more succinct

### CODE REVIEW

**Comment by ddavies-r7** [comment]
Just spotted an issue - brew installs will fail.
I will correct this.

**Comment by ddavies-r7** [comment]
dist is missing - that needs to be added into the build script to create that dir if missing.

**Comment by ddavies-r7** [comment]
This script has the potential to be run on arm64 linux machines also - the build script needs updated to take that into consideration

**Comment by ddavies-r7** [comment]
@vbronov-r7 if you get a moment it would be good if we could get this patched up for others since the m1 proliferation is happening now.

**Comment by dgreene-r7** [comment]
@ddavies-r7 I'm working on a larger refactor of the codebase that will include universal builds. Stay tuned!

**Comment by dgreene-r7** [comment]
Fixed in #217

**Pull request closed without merging**
